# 단일 인스턴스 배포
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  # 테스트용 스키마 사용
  useTestSchema: true

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

singleBinary:
  replicas: 1

  nodeSelector:
    workload: monitoring

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

# 분산 배포 컴포넌트 비활성화
backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

# 캐시 컴포넌트 비활성화
chunksCache:
  enabled: false

resultsCache:
  enabled: false
