prometheus:
  prometheusSpec:
    nodeSelector:
      workload: monitoring
    retention: 3d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

grafana:
  nodeSelector:
    workload: monitoring
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

alertmanager:
  enabled: false
