prometheus:
  prometheusSpec:
    nodeSelector:
      workload: monitoring
    retention: 3d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

prometheusOperator:
  nodeSelector:
    workload: monitoring

grafana:
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts: []
    path: /monitor
    pathType: Prefix
  grafana.ini:
    server:
      root_url: /monitor/
      serve_from_sub_path: true
  nodeSelector:
    workload: monitoring
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

alertmanager:
  enabled: false
